name: Actualizar CSV de Hacienda
on:
  workflow_dispatch: 

jobs:
  descarga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Descargar Directo
        run: |
          # Descarga el CSV usando tu Token y IDs exactos
          curl -v -L "https://api.airtable.com/v0/appqzHunqskWZJNc2/tblWiTUee1VWK9OZ2?api_key=${{ secrets.AIRTABLE_API }}&output=csv" \
          -o datos_censo.csv
          
          # Verifica si el archivo tiene datos o error
          cat datos_censo.csv

      - name: Guardar en GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add datos_censo.csv
          git commit -m "Sincronización: $(date +'%d-%m-%Y %H:%M')" || exit 0
          git push origin main
