name: Actualizar CSV de Hacienda
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11-21/2 * * 1-5'

jobs:
  descarga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Descargar de Airtable
        env:
          AIRTABLE_API: ${{ secrets.AIRTABLE_API }}
        run: |
          pip install requests
          python - <<EOF
          import os, requests, csv
          token = os.environ.get("AIRTABLE_API")
          base_id = "appqzHunqskWZJNc2"
          table_id = "tblWiTUee1VWK9OZ2"
          url = f"https://api.airtable.com/v0/{base_id}/{table_id}"
          headers = {"Authorization": f"Bearer {token}"}
          res = requests.get(url, headers=headers)
          data = res.json()
          if "records" in data:
              filas = [r["fields"] for r in data.get("records", [])]
              if filas:
                  columnas = set()
                  for f in filas: columnas.update(f.keys())
                  with open("datos_censo.csv", "w", newline="", encoding="utf-8") as f:
                      writer = csv.DictWriter(f, fieldnames=list(columnas))
                      writer.writeheader()
                      writer.writerows(filas)
                  print("Archivo generado localmente")
          else:
              print("Error en data:", data)
              exit(1)
          EOF

      - name: Forzar Guardado en GitHub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add datos_censo.csv
          git commit -m "Sincronizacion Forzada Hacienda" || echo "Sin cambios"
          git push
